### PR TITLE
added test cases

### PR DESCRIPTION
**Pull request by thevaachandereng**
I added more test cases to improve codecov.

### CODE REVIEW

**Comment by agitter** [comment]
> Is this a floating point issue? I can spend time tomorrow to look more in detail.

Probably.  What do you get when you run `wt.corr(1:6, 2:7, rep(0, 6))` locally?

I expect the floating point problem is introduced in the line `w <- w / sum(w)`.  Does the test case pass if you use vectors of length 8 instead of 6?

**Comment by agitter** [comment]
The precision is closer but there is still an error
> 1 - 1 == -8.67e-05

**Comment by agitter** [comment]
In c037789 I added a `tolerance` to address the floating point error.  I think this is preferable to rounding values in test cases.  The `tolerance` and `scale` (not needed) are explained [here](https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/all.equal).

@thevaachandereng you can merge if everything looks good to you.

**Comment by thevaachandereng** [comment]
This looks good. Sorry I was working on it little late. I was going to fix it today but thanks for fixing this. I hope our package is 100% tested now.

**Pull request merged**
