### PR TITLE
Move binder to new repo and add news

### PR DESCRIPTION
**Pull request by thevaachandereng**

### CODE REVIEW

**Comment by thevaachandereng** [comment]
please keep this open, I still have things to work on.

**Comment by agitter** [comment]
Let's also add the new readme subsection describing the purpose of the LPWC-examples repository in this pull request.

**Comment by thevaachandereng** [comment]
Yes, that was the other part I wanted to add before merging this.

**Comment by thevaachandereng** [comment]
We can merge this once you look through all the changes.

**Pull request merged**
